// The question bank as the Functions see it. bank.data.js is generated by
// scripts/import_questions.mjs from the reference pages; nothing in it is hand-edited.
// Answers and explanations never leave this module in bulk: the exam endpoints strip
// them on the way out and only return them for a graded attempt.
import { PARTS } from './bank.data.js';

const all = () => PARTS.flatMap((p) => p.questions);
const allDrills = () => PARTS.flatMap((p) => p.drills);

export function counts() {
  return PARTS.map((p) => ({ part: p.part, partTitle: p.partTitle, questions: p.questions.length, drills: p.drills.length, topics: p.counts.topics }));
}

export function questionById(id) { return all().find((q) => q.id === id) || null; }
export function drillById(id) { return allDrills().find((d) => d.id === id) || null; }

// Unbiased Fisher–Yates with crypto randomness.
export function shuffle(arr) {
  const a = arr.slice();
  const r = new Uint32Array(a.length);
  crypto.getRandomValues(r);
  for (let i = a.length - 1; i > 0; i--) {
    const j = r[i] % (i + 1);
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// Stratified so a mixed-part exam holds parts in proportion to their bank size, and a
// single part spreads across its domains rather than clustering in one section.
export function sampleQuestions({ parts, count, domain }) {
  let pool = all().filter((q) => parts.includes(q.part));
  if (domain) pool = pool.filter((q) => q.domain === domain);
  if (pool.length <= count) return shuffle(pool);
  const byDomain = new Map();
  for (const q of pool) (byDomain.get(q.domain) || byDomain.set(q.domain, []).get(q.domain)).push(q);
  const out = [];
  const domains = [...byDomain.entries()];
  const total = pool.length;
  let assigned = 0;
  for (const [, qs] of domains) {
    const take = Math.floor((qs.length / total) * count);
    out.push(...shuffle(qs).slice(0, take));
    assigned += take;
  }
  // Fill any rounding shortfall from the leftovers.
  const chosen = new Set(out.map((q) => q.id));
  for (const q of shuffle(pool)) {
    if (assigned >= count) break;
    if (!chosen.has(q.id)) { out.push(q); chosen.add(q.id); assigned++; }
  }
  return shuffle(out);
}

export function sampleDrills({ parts, count, domain }) {
  let pool = allDrills().filter((d) => parts.includes(d.part));
  if (domain) pool = pool.filter((d) => d.domain === domain);
  return shuffle(pool).slice(0, count);
}

export const publicQuestion = (q) => ({ id: q.id, code: q.code, part: q.part, domain: q.domain, domainTitle: q.domainTitle, section: q.section, sectionTitle: q.sectionTitle, stem: q.stem, options: q.options });
export const publicDrill = (d) => ({ id: d.id, code: d.code, part: d.part, domain: d.domain, domainTitle: d.domainTitle, section: d.section, sectionTitle: d.sectionTitle, prompt: d.prompt });
