// Regenerates docs/PROGRESS.md from the outline and the content files.
// The outline in src/data/topics.json is the master checklist; this renders it
// with the current status, word count, and review date of every page.
//
//   npm run progress          rewrite docs/PROGRESS.md
//   npm run progress -- --check   fail if the file is out of date (for CI)
import fs from 'node:fs';
import path from 'node:path';

const OUT = 'docs/PROGRESS.md';
const CHECK = process.argv.includes('--check');
const outline = JSON.parse(fs.readFileSync('src/data/topics.json', 'utf8'));

const words = body => body.replace(/<[^>]+>/g, ' ').split(/\s+/).filter(Boolean).length;

function pageFor(topicPath) {
  // /representation/a/b/c/ -> src/content/topics/representation/a/b/c.md
  const file = path.join('src/content/topics', topicPath.replace(/^\/|\/$/g, '')) + '.md';
  if (!fs.existsSync(file)) return null;
  const src = fs.readFileSync(file, 'utf8');
  const fm = src.match(/^---\n([\s\S]*?)\n---/)?.[1] ?? '';
  return {
    status: fm.match(/^status:\s*(\w+)/m)?.[1] ?? 'stub',
    reviewed: fm.match(/^lastReviewed:\s*"?(\d{4}-\d{2}-\d{2})/m)?.[1] ?? '',
    words: words(src.slice(fm.length + 8)),
  };
}

const rows = [];
for (const part of outline.parts) {
  for (const domain of part.domains) {
    for (const section of domain.sections) {
      for (const topic of section.topics) {
        rows.push({ part, domain, section, topic, page: pageFor(topic.path) });
      }
    }
  }
}

const STATUSES = ['stub', 'draft', 'review', 'published'];
const tally = list => STATUSES.map(s => list.filter(r => (r.page?.status ?? 'stub') === s).length);

const lines = [];
lines.push('# Progress');
lines.push('');
lines.push('Generated by `npm run progress` — do not edit by hand. The outline in');
lines.push('`src/data/topics.json` is the master checklist; every topic below has a page file,');
lines.push('and `status` is the only thing that says whether it is finished. Only `published`');
lines.push('is indexed, and only the owner moves a page there (see `docs/VERIFICATION.md`).');
lines.push('');
lines.push('## Summary');
lines.push('');
lines.push('| Part | Topics | ' + STATUSES.map(s => s[0].toUpperCase() + s.slice(1)).join(' | ') + ' | Words |');
lines.push('|---|---:|---:|---:|---:|---:|---:|');
for (const part of outline.parts) {
  const list = rows.filter(r => r.part === part);
  lines.push(`| ${part.part}. ${part.name} | ${list.length} | ${tally(list).join(' | ')} | ${list.reduce((a, r) => a + (r.page?.words ?? 0), 0).toLocaleString('en-US')} |`);
}
lines.push(`| **All parts** | **${rows.length}** | ${tally(rows).map(n => `**${n}**`).join(' | ')} | **${rows.reduce((a, r) => a + (r.page?.words ?? 0), 0).toLocaleString('en-US')}** |`);
lines.push('');

for (const part of outline.parts) {
  lines.push(`## Part ${part.part} — ${part.name}`);
  lines.push('');
  for (const domain of part.domains) {
    lines.push(`### ${domain.code} ${domain.title}`);
    lines.push('');
    for (const section of domain.sections) {
      lines.push(`**${section.code} ${section.title}**`);
      lines.push('');
      lines.push('| Code | Title | Status | Words | Last reviewed |');
      lines.push('|---|---|---|---:|---|');
      for (const { topic, page } of rows.filter(r => r.section === section)) {
        const status = page?.status ?? 'missing';
        const mark = status === 'published' ? '**published**' : status;
        lines.push(`| ${topic.code} | [${topic.title}](${topic.path}) | ${mark} | ${page?.words ? page.words.toLocaleString('en-US') : '—'} | ${page?.reviewed || '—'} |`);
      }
      lines.push('');
    }
  }
}

const next = lines.join('\n');
if (CHECK) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (current !== next) { console.log(`progress: ${OUT} is out of date — run \`npm run progress\``); process.exit(1); }
  console.log(`progress: ${OUT} is current`);
} else {
  fs.writeFileSync(OUT, next);
  const [stub, draft, review, published] = tally(rows);
  console.log(`progress: wrote ${OUT} — ${rows.length} topics (${stub} stub · ${draft} draft · ${review} review · ${published} published)`);
}
